name: Deploy-ssh
on:
  push:
    branches:
      - prod
jobs:
  lint:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t toezbitaisoft/test-gh-action:latest .
      - name: Push Docker Image
        run: docker push toezbitaisoft/test-gh-action:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
            docker login & docker pull toezbit/test-gh-action:latest & docker run -p 1573:8888 -d --name my-express toezbit/test/gh-action:latest
